### ISSUE TITLE
Delete Klas Api Error

### ISSUE THREAD

**Issue by Devilskey** [TamoAgzt/Smort-Examen-Tool-API#19]
The Error
```
ERROR:` Table 'SmortTestDb.User' doesn't exist : System.Collections.ListDictionaryInternal : MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'SmortTestDb.User' doesn't exist
   at MySql.Data.MySqlClient.MySqlStream.ReadPacketAsync(Boolean execAsync)
   at MySql.Data.MySqlClient.NativeDriver.GetResultAsync(Int32 affectedRow, Int64 insertedId, Boolean execAsync)
   at MySql.Data.MySqlClient.Driver.GetResultAsync(Int32 statementId, Int32 affectedRows, Int64 insertedId, Boolean execAsync)
   at MySql.Data.MySqlClient.Driver.NextResultAsync(Int32 statementId, Boolean force, Boolean execAsync)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResultAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(Boolean execAsync, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at VistaExamenPlanner.Handler.DatabaseHandler.ExecuteInsertDeleteUpdate(MySqlCommand sqlCommand, String functie) in /src/VistaExamenPlanner.Handler/DatabaseHandler.cs:line 46 : Delete
2023-11-01 13:04:26.378 [INF] HTTP DELETE /DeleteKlas responded 200 in 12.9787 ms
```

**Comment by Devilskey** [comment]
Possible Fix Edit the sql command so that it will change from user to gebruikers
